package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/lucavb/terraform-provider-netgear-plus/internal/cfg"
	"github.com/lucavb/terraform-provider-netgear-plus/internal/model"
)

// portCount is the fixed GS108Ev3 port count.
const portCount = 8

// options controls how a parsed backup is rendered to Terraform
// configuration. Tests set the fields directly.
type options struct {
	// SourcePath is the backup path recorded in the generated header comment.
	SourcePath string
	Host       string
	Model      string
	Name       string
	Serial     string

	// HostInferred marks Host as decoded from the backup's ethconfig
	// section rather than passed via -host; it adds a verification hint
	// to the generated header comment.
	HostInferred bool

	AllowDeletions bool
	SkipImport     bool
	Force          bool
}

// render converts a parsed FMv2 backup into Terraform configuration text.
//
// It returns the rendered configuration and any validation warnings. An
// empty string with a non-nil error slice marks a fatal problem: a section
// decode failure, a backup with no VLAN entries, or — unless Force is set —
// a state that fails model.VLANState.Validate. With Force set, validation
// failures are downgraded to warnings and the configuration is rendered
// anyway.
func render(c *cfg.Config, opts options) (string, []error) {
	vlans, err := c.VLANs()
	if err != nil {
		return "", []error{fmt.Errorf("decode vlan section: %w", err)}
	}

	pvids, err := c.PVIDs()
	if err != nil {
		return "", []error{fmt.Errorf("decode pvid section: %w", err)}
	}

	// The resource schema requires at least one vlan block, so an empty
	// VLAN table is fatal even with Force.
	if len(vlans) == 0 {
		return "", []error{fmt.Errorf("no VLAN entries found in config")}
	}

	state := buildState(vlans, pvids).Normalize()

	var warnings []error
	if err := state.Validate(); err != nil {
		if !opts.Force {
			return "", []error{err}
		}
		warnings = append(warnings, err)
	}

	return renderHCL(state, c.Fingerprint(), opts), warnings
}

// buildState converts decoded backup sections into the canonical model
// state. Ignored ports are left unset; Normalize fills them in.
func buildState(vlans []cfg.VLAN, pvids []int) model.VLANState {
	state := model.VLANState{
		PortCount: portCount,
		VLANs:     make(map[int]model.Vlan, len(vlans)),
		PVIDs:     make(map[int]int, len(pvids)),
	}

	for _, vlan := range vlans {
		ports := make(map[int]model.PortMembership, len(vlan.Members))
		for _, port := range vlan.Untagged {
			ports[port] = model.PortMembershipUntagged
		}
		for _, port := range vlan.Tagged {
			ports[port] = model.PortMembershipTagged
		}
		state.VLANs[vlan.ID] = model.Vlan{ID: vlan.ID, Ports: ports}
	}

	for idx, pvid := range pvids {
		state.PVIDs[idx+1] = pvid
	}

	return state
}

// renderHCL emits the final Terraform configuration. The output is
// byte-stable for a given backup and options, and is formatted so that
// terraform fmt is a no-op: consecutive single-line attributes have their
// = signs aligned within each block.
func renderHCL(state model.VLANState, fingerprint string, opts options) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by cfg2tf from %s (FMv2 checksum %s)\n", opts.SourcePath, fingerprint)
	if opts.HostInferred {
		fmt.Fprintf(&b, "# Host %s was inferred from the backup's ethconfig section; verify it still matches the live switch.\n", opts.Host)
	}
	b.WriteString("\n")

	b.WriteString("terraform {\n")
	b.WriteString("  required_providers {\n")
	b.WriteString("    netgear = {\n")
	b.WriteString("      source = \"lucavb/netgear-plus\"\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	b.WriteString("variable \"switch_password\" {\n")
	b.WriteString("  type      = string\n")
	b.WriteString("  sensitive = true\n")
	b.WriteString("}\n")
	b.WriteString("\n")

	b.WriteString("provider \"netgear\" {\n")
	fmt.Fprintf(&b, "  host     = %s\n", quoteHCL(opts.Host))
	b.WriteString("  password = var.switch_password\n")
	fmt.Fprintf(&b, "  model    = %s\n", quoteHCL(opts.Model))
	b.WriteString("}\n")
	b.WriteString("\n")

	serialRef := "data.netgear_plus_switch.target.serial_number"
	if opts.Serial != "" {
		serialRef = quoteHCL(opts.Serial)
	} else {
		b.WriteString("data \"netgear_plus_switch\" \"target\" {}\n")
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "resource \"netgear_plus_vlan_state\" %s {\n", quoteHCL(opts.Name))
	fmt.Fprintf(&b, "  expected_serial_number = %s\n", serialRef)
	fmt.Fprintf(&b, "  allow_vlan_deletions   = %t\n", opts.AllowDeletions)
	b.WriteString("\n")

	for _, vid := range state.VLANIDs() {
		vlan := state.VLANs[vid]
		fmt.Fprintf(&b, "  vlan {\n    id = %d\n    ports = {\n", vid)
		for _, port := range state.SortedPorts() {
			fmt.Fprintf(&b, "      %s = %s\n", quoteHCL(strconv.Itoa(port)), quoteHCL(string(vlan.Ports[port])))
		}
		b.WriteString("    }\n  }\n\n")
	}

	b.WriteString("  pvids = {\n")
	for _, port := range state.SortedPorts() {
		fmt.Fprintf(&b, "    %s = %d\n", quoteHCL(strconv.Itoa(port)), state.PVIDs[port])
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")

	if !opts.SkipImport {
		importID := opts.Model + "@" + opts.Host
		b.WriteString("\n")
		b.WriteString("# CLI alternative (Terraform/OpenTofu support config-driven `import` blocks natively):\n")
		fmt.Fprintf(&b, "# terraform import netgear_plus_vlan_state.%s %s\n", opts.Name, importID)
		b.WriteString("import {\n")
		fmt.Fprintf(&b, "  to = netgear_plus_vlan_state.%s\n", opts.Name)
		fmt.Fprintf(&b, "  id = %s\n", quoteHCL(importID))
		b.WriteString("}\n")
	}

	return b.String()
}

// quoteHCL quotes s for use in a double-quoted HCL string literal,
// escaping backslashes and double quotes.
func quoteHCL(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
