package main

import (
	"encoding/binary"
	"strings"
	"testing"

	"github.com/lucavb/terraform-provider-netgear-plus/internal/cfg"
)

// All fixtures are assembled synthetically in test code; real backups
// contain password material and must never be used as test input.

const (
	testTag       = 1
	fileHeaderLen = 8
	vlanHeaderLen = 4
	vlanEntryLen  = 4
	sectionHeader = 4
)

// fixture assembles a synthetic FMv2 backup from section records.
func fixture(t *testing.T, sections ...[]byte) []byte {
	t.Helper()

	var payload []byte
	for _, section := range sections {
		payload = append(payload, section...)
	}

	checksum, err := cfg.Checksum(payload)
	if err != nil {
		t.Fatalf("Checksum() error = %v", err)
	}

	data := make([]byte, fileHeaderLen, fileHeaderLen+len(payload))
	copy(data[0:4], "FMv2")
	binary.BigEndian.PutUint16(data[4:6], uint16(len(payload)))
	binary.BigEndian.PutUint16(data[6:8], checksum)

	return append(data, payload...)
}

// writeSection builds one section record: uint16 BE tag, uint16 BE length,
// then name + NUL + data.
func writeSection(name string, data []byte) []byte {
	body := append(append([]byte(name), 0), data...)

	section := make([]byte, sectionHeader, sectionHeader+len(body))
	binary.BigEndian.PutUint16(section[0:2], testTag)
	binary.BigEndian.PutUint16(section[2:4], uint16(len(body)))

	return append(section, body...)
}

// vlanSection builds the vlan section: uint16 LE mode, uint16 LE count, then
// entries of uint16 LE vid + uint16 LE mask (low byte = member bitmap, high
// byte = untagged bitmap).
func vlanSection(mode uint16, entries ...[2]uint16) []byte {
	data := make([]byte, vlanHeaderLen, vlanHeaderLen+len(entries)*vlanEntryLen)
	binary.LittleEndian.PutUint16(data[0:2], mode)
	binary.LittleEndian.PutUint16(data[2:4], uint16(len(entries)))
	for _, entry := range entries {
		var encoded [vlanEntryLen]byte
		binary.LittleEndian.PutUint16(encoded[0:2], entry[0])
		binary.LittleEndian.PutUint16(encoded[2:4], entry[1])
		data = append(data, encoded[:]...)
	}
	return writeSection("vlan", data)
}

// pvidSection builds the pvid section: 16 bytes of 8 uint16 LE values.
func pvidSection(pvids ...int) []byte {
	data := make([]byte, 16)
	for port, pvid := range pvids {
		binary.LittleEndian.PutUint16(data[port*2:], uint16(pvid))
	}
	return writeSection("pvid", data)
}

func parseFixture(t *testing.T, sections ...[]byte) *cfg.Config {
	t.Helper()

	config, err := cfg.ParseConfig(fixture(t, sections...))
	if err != nil {
		t.Fatalf("ParseConfig() error = %v", err)
	}
	return config
}

// goldenConfig decodes two VLANs that exercise every membership value:
// VLAN 1 with untagged ports 1,2,5,6,7 and tagged port 8, and VLAN 10 with
// untagged ports 3,4 and tagged port 8. PVIDs map ports 3,4 to 10 and the
// rest to 1, so the state passes model.VLANState.Validate. The synthetic
// payload checksums to 0x6337.
func goldenConfig(t *testing.T) *cfg.Config {
	t.Helper()

	return parseFixture(t,
		vlanSection(4, [2]uint16{1, 0x73D3}, [2]uint16{10, 0x0C8C}),
		pvidSection(1, 1, 10, 10, 1, 1, 1, 1),
	)
}

func goldenOptions() options {
	return options{
		SourcePath: "test.cfg",
		Host:       "192.0.2.10",
		Model:      "gs108ev3",
		Name:       "switch",
	}
}

// ethSection builds the ethconfig section: 1 mode byte + IPv4 10.0.2.2 +
// netmask 255.255.0.0 + gateway 10.0.0.1, matching the real GS108Ev3
// backup's layout.
func ethSection() []byte {
	return writeSection("ethconfig", []byte{0x01, 0x0A, 0x00, 0x02, 0x02, 0xFF, 0xFF, 0x00, 0x00, 0x0A, 0x00, 0x00, 0x01})
}

// paddingSection returns an unrelated even-length section so the total
// payload stays even, as the format requires.
func paddingSection() []byte {
	return writeSection("misc", []byte{0x00, 0x01})
}

const goldenWant = `# Generated by cfg2tf from test.cfg (FMv2 checksum 6337)

terraform {
  required_providers {
    netgear_plus = {
      source = "lucavb/netgear-plus"
    }
  }
}

variable "switch_password" {
  type      = string
  sensitive = true
}

provider "netgear_plus" {
  host     = "192.0.2.10"
  password = var.switch_password
  model    = "gs108ev3"
}

data "netgear_plus_switch" "target" {}

resource "netgear_plus_vlan_state" "switch" {
  expected_serial_number = data.netgear_plus_switch.target.serial_number
  allow_vlan_deletions   = false

  vlan {
    id = 1
    ports = {
      "1" = "untagged"
      "2" = "untagged"
      "3" = "ignored"
      "4" = "ignored"
      "5" = "untagged"
      "6" = "untagged"
      "7" = "untagged"
      "8" = "tagged"
    }
  }

  vlan {
    id = 10
    ports = {
      "1" = "ignored"
      "2" = "ignored"
      "3" = "untagged"
      "4" = "untagged"
      "5" = "ignored"
      "6" = "ignored"
      "7" = "ignored"
      "8" = "tagged"
    }
  }

  pvids = {
    "1" = 1
    "2" = 1
    "3" = 10
    "4" = 10
    "5" = 1
    "6" = 1
    "7" = 1
    "8" = 1
  }
}

# CLI alternative (Terraform/OpenTofu support config-driven ` + "`import`" + ` blocks natively):
# terraform import netgear_plus_vlan_state.switch gs108ev3@192.0.2.10
import {
  to = netgear_plus_vlan_state.switch
  id = "gs108ev3@192.0.2.10"
}
`

func TestRenderGolden(t *testing.T) {
	t.Parallel()

	got, problems := render(goldenConfig(t), goldenOptions())
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	if got != goldenWant {
		t.Fatalf("render() output does not match the golden config.\n--- got ---\n%s\n--- want ---\n%s", got, goldenWant)
	}

	// The golden comparison covers these, but assert the contract
	// explicitly so a golden edit cannot silently drop them.
	for _, want := range []string{
		`data "netgear_plus_switch" "target" {}`,
		"expected_serial_number = data.netgear_plus_switch.target.serial_number",
		`id = "gs108ev3@192.0.2.10"`,
		`"8" = "tagged"`,
		`"3" = "ignored"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("render() output missing %q", want)
		}
	}

	// Full 8-port coverage in every ports map and in pvids.
	for port := 1; port <= 8; port++ {
		if strings.Count(got, "\""+string(rune('0'+port))+"\" = ") != 3 {
			t.Errorf("render() output does not cover port %d in all 3 maps", port)
		}
	}

	// VLAN blocks sorted ascending.
	if strings.Index(got, "id = 10") < strings.Index(got, "id = 1\n") {
		t.Error("render() output does not sort vlan blocks ascending by id")
	}
}

func TestRenderSerialLiteral(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.Serial = "123A456"

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	if !strings.Contains(got, `expected_serial_number = "123A456"`) {
		t.Error(`render() output missing literal serial "123A456"`)
	}
	if strings.Contains(got, "netgear_plus_switch") {
		t.Error("render() output must not reference the switch data source when -serial is set")
	}
}

func TestRenderSkipImport(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.SkipImport = true

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	if strings.Contains(got, "import {") {
		t.Error("render() output must not contain an import block with -skip-import")
	}
	if strings.Contains(got, "# terraform import") {
		t.Error("render() output must not contain the CLI import comment with -skip-import")
	}
}

func TestRenderAllowDeletions(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.AllowDeletions = true

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	if !strings.Contains(got, "allow_vlan_deletions   = true") {
		t.Error(`render() output missing "allow_vlan_deletions   = true"`)
	}
}

func TestRenderCustomName(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.Name = "lab"

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	for _, want := range []string{
		`resource "netgear_plus_vlan_state" "lab" {`,
		"to = netgear_plus_vlan_state.lab",
		"# terraform import netgear_plus_vlan_state.lab gs108ev3@192.0.2.10",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("render() output missing %q", want)
		}
	}
}

func TestRenderValidationFailureAndForce(t *testing.T) {
	t.Parallel()

	// VLAN 1 only, with a PVID pointing at nonexistent VLAN 99.
	config := parseFixture(t,
		vlanSection(4, [2]uint16{1, 0xFFFF}),
		pvidSection(1, 1, 99, 1, 1, 1, 1, 1),
	)

	opts := goldenOptions()
	got, problems := render(config, opts)
	if got != "" {
		t.Fatalf("render() without force returned output, want none")
	}
	if len(problems) == 0 {
		t.Fatal("render() without force returned no problems")
	}
	if !strings.Contains(problems[0].Error(), "does not exist") {
		t.Errorf("render() problem = %v, want a missing-VLAN error", problems[0])
	}

	opts.Force = true
	got, problems = render(config, opts)
	if got == "" {
		t.Fatal("render() with force returned no output")
	}
	if len(problems) == 0 {
		t.Error("render() with force returned no warnings")
	} else if !strings.Contains(problems[0].Error(), "does not exist") {
		t.Errorf("render() warning = %v, want a missing-VLAN warning", problems[0])
	}
	if !strings.Contains(got, `"3" = 99`) {
		t.Error("render() with force must still emit the pvids map")
	}
}

func TestRenderZeroVLANs(t *testing.T) {
	t.Parallel()

	config := parseFixture(t,
		vlanSection(4),
		pvidSection(1, 1, 1, 1, 1, 1, 1, 1),
	)

	got, problems := render(config, goldenOptions())
	if got != "" {
		t.Fatal("render() returned output for a config with no VLANs")
	}
	if len(problems) != 1 || !strings.Contains(problems[0].Error(), "no VLAN entries found in config") {
		t.Fatalf("render() problems = %v, want single %q error", problems, "no VLAN entries found in config")
	}
}

func TestRenderEscapesHost(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.Host = `sw"itch\1`

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}
	if !strings.Contains(got, `host     = "sw\"itch\\1"`) {
		t.Error(`render() output missing escaped host "sw\"itch\\1"`)
	}
	if !strings.Contains(got, `id = "gs108ev3@sw\"itch\\1"`) {
		t.Error(`render() output missing escaped import id`)
	}
	if strings.Contains(got, `"sw"itch`) {
		t.Error("render() output contains an unescaped double quote in the host")
	}
}

func TestResolveHost(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		config      func(t *testing.T) *cfg.Config
		opts        func(t *testing.T) options
		wantHost    string
		wantDerived bool
		wantErr     string
	}{
		"explicit host passes through": {
			config:   goldenConfig,
			opts:     func(t *testing.T) options { return goldenOptions() },
			wantHost: "192.0.2.10",
		},
		"empty host infers from ethconfig": {
			config: func(t *testing.T) *cfg.Config {
				return parseFixture(t,
					vlanSection(4, [2]uint16{1, 0x73D3}, [2]uint16{10, 0x0C8C}),
					pvidSection(1, 1, 10, 10, 1, 1, 1, 1),
					ethSection(),
					paddingSection(),
				)
			},
			opts: func(t *testing.T) options {
				opts := goldenOptions()
				opts.Host = ""
				return opts
			},
			wantHost:    "10.0.2.2",
			wantDerived: true,
		},
		"empty host without ethconfig errors": {
			config: goldenConfig,
			opts: func(t *testing.T) options {
				opts := goldenOptions()
				opts.Host = ""
				return opts
			},
			wantErr: "no -host given and the backup has no usable ethconfig section",
		},
		"empty host with malformed ethconfig errors": {
			config: func(t *testing.T) *cfg.Config {
				return parseFixture(t, writeSection("ethconfig", make([]byte, 12)))
			},
			opts: func(t *testing.T) options {
				opts := goldenOptions()
				opts.Host = ""
				return opts
			},
			wantErr: "no -host given and the backup's ethconfig section is unusable",
		},
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			resolved, err := resolveHost(test.config(t), test.opts(t))
			if test.wantErr != "" {
				if err == nil {
					t.Fatalf("resolveHost() = %+v, want error containing %q", resolved, test.wantErr)
				}
				if !strings.Contains(err.Error(), test.wantErr) {
					t.Fatalf("resolveHost() error = %v, want error containing %q", err, test.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("resolveHost() error = %v", err)
			}
			if resolved.Host != test.wantHost {
				t.Errorf("resolveHost() Host = %q, want %q", resolved.Host, test.wantHost)
			}
			if resolved.HostInferred != test.wantDerived {
				t.Errorf("resolveHost() HostInferred = %t, want %t", resolved.HostInferred, test.wantDerived)
			}
		})
	}
}

func TestRenderInferredHostComment(t *testing.T) {
	t.Parallel()

	opts := goldenOptions()
	opts.Host = "10.0.2.2"
	opts.HostInferred = true

	got, problems := render(goldenConfig(t), opts)
	if len(problems) != 0 {
		t.Fatalf("render() problems = %v, want none", problems)
	}

	wantHeader := "# Generated by cfg2tf from test.cfg (FMv2 checksum 6337)\n" +
		"# Host 10.0.2.2 was inferred from the backup's ethconfig section; verify it still matches the live switch.\n\n"
	if !strings.HasPrefix(got, wantHeader) {
		t.Fatalf("render() header does not carry the inference comment.\n--- got ---\n%s\n--- want ---\n%s", got, wantHeader)
	}
	if !strings.Contains(got, `host     = "10.0.2.2"`) {
		t.Error(`render() output missing inferred host "10.0.2.2"`)
	}
	if !strings.Contains(got, `id = "gs108ev3@10.0.2.2"`) {
		t.Error(`render() output missing import id "gs108ev3@10.0.2.2"`)
	}
}
